export const books = [
  {
    id: 1,
    title: 'Book 1',
    author: 'The author',
    description: 'Intro about the book',
    image: '/images/book1.jpg',
    genre: 'The genre',
    owner: 'name of the owner',
    isAvailable: false,
  },
  {
    id: 2,
    title: 'Book 2',
    author: 'The author',
    description: 'Intro about the book',
    image: '/images/book2.jpg',
    genre: 'The genre',
    owner: 'name of the owner',
    isAvailable: true,
  },
  {
    id: 3,
    title: 'Book 3',
    author: 'The author',
    description: 'Intro about the book',
    image: '/images/book3.jpg',
    genre: 'The genre',
    owner: 'name of the owner',
    isAvailable: false,
  },
  {
    id: 4,
    title: 'Book 4',
    author: 'The author',
    description: 'Intro about the book',
    image: '/images/book4.jpg',
    genre: 'The genre',
    owner: 'name of the owner',
    isAvailable: true,
  },
  {
    id: 5,
    title: 'Book 5',
    author: 'The author',
    description: 'Intro about the book',
    image: '/images/book5.jpg',
    genre: 'The genre',
    owner: 'name of the owner',
    isAvailable: false,
  },
  {
    id: 6,
    title: 'Book 6',
    author: 'The author',
    description: 'Intro about the book',
    image: '/images/book6.jpg',
    genre: 'The genre',
    owner: 'name of the owner',
    isAvailable: true,
  },
  {
    id: 7,
    title: 'Book 7',
    author: 'The author',
    description: 'Intro about the book',
    image: '/images/book7.jpg',
    genre: 'The genre',
    owner: 'name of the owner',
    isAvailable: false,
  },
  {
    id: 8,
    title: 'Book 8',
    author: 'The author',
    description: 'Intro about the book',
    image: '/images/book8.jpg',
    genre: 'The genre',
    owner: 'name of the owner',
    isAvailable: true,
  },
];
