export enum bookUpdateActionTypes {
  BOOK_UPDATE_REQUEST = 'BOOK_UPDATE_REQUEST',
  BOOK_UPDATE_SUCCESS = 'BOOK_UPDATE_SUCCESS',
  BOOK_UPDATE_FAILURE = 'BOOK_UPDATE_FAILURE',
  BOOK_UPDATE_RESET = 'BOOK_UPDATE_RESET',
}
