export enum bookCreateActionTypes {
  BOOK_CREATE_REQUEST = 'BOOK_CREATE_REQUEST',
  BOOK_CREATE_SUCCESS = 'BOOK_CREATE_SUCCESS',
  BOOK_CREATE_FAILURE = 'BOOK_CREATE_FAILURE',
  BOOK_CREATE_RESET = 'BOOK_CREATE_RESET',
}
